services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  server:
    image: ghcr.io/zab3355/a-shore-server:latest
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/your-database-name
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=YourSessionSecret
    depends_on:
      - mongo
      - redis

  ui:
    image: ghcr.io/zab3355/a-shore-ui:latest
    ports:
      - "4200:4200"
    depends_on:
      - server
      
volumes:
  mongo-data:
