version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: ./  # Project root
      dockerfile: server/Dockerfile.server
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/your-database-name
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=YourSessionSecret
    depends_on:
      - mongo
      - redis

  ui:
    build:
      context: ./  # Project root
      dockerfile: src/Dockerfile.ui
    container_name: ui
    ports:
      - "4200:4200"
    depends_on:
      - server

volumes:
  mongo-data:
